#Pflichtfeld - Version von Kubernetes API (POD - v1, Service - v1, ReplicaSet - apps/v1, Deployment - apps/v1)
apiVersion: v1
#Pflichtfeld - Typ, welcher erstellt werden soll (POD, Service, ReplicaSet, Deployment)
kind: Service
#Pflichtfeld - Daten zum Objekt, welcher erstellt wird.
metadata:
    name: myapp-service
#Pflichtfeld - Spezifikation zum Objekt, welcher man erstellt möchte
spec:
    type: NodePort
    ports:
    - targetPort: 80
      port: 80
      NodePort: 30008
    selector:
      app: myapp
      type: front-end  