apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end
spec:
  selector:
    #label muss gleich sein wie bei Template
    matchLabels:
      type: front-end
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx
          image: nginx